#!/usr/bin/python
# This file is modified to adopt MidoNet.
# EASY-INSTALL-ENTRY-SCRIPT: 'deimos==0.4.0','console_scripts','deimos'
__requires__ = 'deimos==0.4.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('deimos==0.4.0', 'console_scripts', 'deimos')()
    )